apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lj9lbsbew-nodejs 
  janus-idp.io/tekton: lj9lbsbew-nodejs
  backstage.io/kubernetes-id: lj9lbsbew-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lj9lbsbew-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  